# 数据库连接
spring:
    datasource:
        driver-class-name : com.mysql.cj.jdbc.Driver
        mysql:
            url : jdbc:mysql://localhost:3306/web?useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&useSSL=true&serverTimezone=UTC
            username : root
            password : root
# 多数据库连接
#    datasource-other:
#        driver-class-name : com.mysql.jdbc.Driver
#        mysql:
#            url: jdbc:mysql://localhost:3306/ofbiz?useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&useSSL=true
#            username: root
#            password: root

# beetlsql配置
beetlsql:
    sqlLoader: /sql





