# 项目相关配置
authority:
  # 名称
  name: authority
  # 版本
  version: 1.0.0
  # 版权年份
  copyrightYear: 2019
  # 获取ip地址开关
  addressEnabled: true
  # 自定义账号
  userName : 999
  # 自定义密码
  passWord: 666

# 开发环境配置
server:
  # 服务端口
  port: 8080
  servlet:
    # 项目contextPath
    context-path: /
  tomcat:
    # tomcat的URI编码
    uri-encoding: UTF-8
    # tomcat最大线程数，默认为200
    max-threads: 800
    # Tomcat启动初始化的线程数，默认值25
    min-spare-threads: 30

# 日志配置

logging:
  config: classpath:log4j2.yml
  level:
    com:
      authority: WARN
    org:
      springframework:
        web: WARN
    root: WARN

# 用户配置
user:
  password:
    # 密码错误{maxRetryCount}次锁定10分钟
    maxRetryCount: 5

# 指定上传文件的地址
file:
  upload:
    path: E:/upload

# Spring配置
spring:
  freemarker:
    cache: false
    charset: UTF-8
    check-template-location: true
    content-type: text/html
    expose-request-attributes: true
    expose-session-attributes: true
    request-context-attribute: request
    settings:
      template_update_delay: 0
    suffix: .ftl
    template-loader-path: classpath:/templates/
  profiles:
    active: db
  resources:
    static-locations: classpath:/static/,classpath:/templates/
  # 服务模块
  devtools:
    restart:
      # 热部署开关
      enabled: true
      #设置重启的目录
      additional-paths: src/main/java/,src/main/resources/templates/,src/main/resources/static/



# Shiro
shiro:
  user:
    # 登录地址
    loginUrl: /login
    # 没有机器码权限跳转地址
    unRegisterUrl: /unRegister
    # 初始密码
    initialPass: 123456
    # 密码加密方式
    hashAlgorithmName: SHA-256
    # 密码加密次数
    hashIterations: 1
    # 权限认证失败地址
    unauthorizedUrl: /unauth
    # 首页地址
    indexUrl: /index
    # 验证码开关
    # captchaEnabled: true
    # 验证码类型 math 数组计算 char 字符
    # captchaType: math
  #cookie:
    # 设置Cookie的域名 默认空，即当前访问的域名
   # domain:
    # 设置cookie的有效访问路径
   # path: /
    # 设置HttpOnly属性
   # httpOnly: true
    # 设置Cookie的过期时间，天为单位
   # maxAge: 30
  session:
    # 此系统支持在线人数最高为几个
    maxUserNum : 2
    # Session超时时间（默认30分钟）
    expireTime: 30
    # 同步session到数据库的周期（默认1分钟）
    dbSyncPeriod: 1
    # 相隔多久检查一次session的有效性，默认就是10分钟
    validationInterval: 10

#单点登录token
jwt:
  #失效时间默认5分钟
  expireTime : 5
  #key
  key : ymh
